ACHV = [
    {"name": "Welcome to Hell", "desc": "Play a game", "type": "game-end", "notes": ""},
    {"name": "Welcome to the Asylum", "desc": "Play a chaos game", "type": "game-end", "notes": ""},
    {
        "name": "Alzheimer's Patient",
        "desc": "Play a game with an amnesia language pack",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "O HAI DER!",
        "desc": "Play a game with Para's secret account (not @para949)",
        "type": "game-end",
        "notes": "",
    },
    {"name": "Spy vs Spy", "desc": "Play a game in secret mode (no role reveal)", "type": "game-end", "notes": ""},
    {
        "name": "Explorer",
        "desc": "Play at least 2 games each in 10 different groups",
        "inactive": True,
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Linguist",
        "desc": "Play at least 2 games each in 10 different language packs",
        "inactive": True,
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "I Have No Idea What I'm Doing",
        "desc": "Play a game in secret amnesia mode",
        "type": "game-end",
        "notes": "",
    },
    {"name": "Enochlophobia", "desc": "Play a 35 player game", "type": "game-end", "notes": ""},
    {"name": "Introvert", "desc": "Play a 5 player game", "type": "game-end", "notes": ""},
    {"name": "Naughty!", "desc": "Play a game using any NSFW language pack", "type": "game-end", "notes": ""},
    {"name": "Dedicated", "desc": "Play 100 games", "type": "game-end", "notes": ""},
    {"name": "Obsessed", "desc": "Play 1000 games", "type": "game-end", "notes": ""},
    {
        "name": "Here's Johnny!",
        "desc": "Get 50 kills as the serial killer",
        "not_via_playing": True,
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "I've Got Your Back",
        "desc": "Save 50 people as the Guardian Angel",
        "not_via_playing": True,
        "type": "instantaneous",
        "notes": "",
    },
    {"name": "Masochist", "desc": "Win a game as the Tanner", "type": "game-end", "notes": ""},
    {
        "name": "Wobble Wobble",
        "desc": "Survive a game as the drunk (at least 10 players)",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Inconspicuous",
        "desc": "In a game of 20 or more people, do not get a single lynch vote against you (and survive)",
        "type": "game-end",
        "notes": "",
    },
    {"name": "Survivalist", "desc": "Survive 100 games", "type": "game-end", "notes": ""},
    {
        "name": "Black Sheep",
        "desc": "Get lynched first 3 games in a row",
        "inactive": True,
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Promiscuous",
        "desc": "As the harlot, survive a 5+ night game without staying home or visiting the same person more than once",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Mason Brother",
        "desc": "Be one of at least two surviving masons in a game",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Double Shifter",
        "desc": "Change roles twice in one game (cult conversion does not count)",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Hey Man, Nice Shot",
        "desc": "As the hunter, use your dying shot to kill a wolf or serial killer",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "That's Why You Don't Stay Home",
        "desc": "As a wolf or cultist, kill or convert a harlot that stayed home",
        "type": "instantaneous",
        "notes": "",
    },
    {"name": "Double Vision", "desc": "Be one of two seers at the same time", "type": "instantaneous", "notes": ""},
    {"name": "Double Kill", "desc": "Be part of the Serial Killer / Hunter ending", "type": "game-end", "notes": ""},
    {"name": "Should Have Known", "desc": "As the Seer, reveal the Beholder", "type": "instantaneous", "notes": ""},
    {
        "name": "I See a Lack of Trust",
        "desc": "As the Seer, get lynched on the first day",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Sunday Bloody Sunday",
        "desc": "Be one of at least 4 victims to die in a single night",
        "type": "instantaneous",
        "notes": "",
    },
    {"name": "Change Sides Works", "desc": "Change roles in a game, and win", "type": "game-end", "notes": ""},
    {
        "name": "Forbidden Love",
        "desc": "Win as a wolf / villager couple (villager, not village team)",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Developer",
        "desc": "Have a pull request merged into the repo",
        "not_via_playing": True,
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "The First Stone",
        "desc": "Be the first to cast a lynch vote 5 times in a single game",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Smart Gunner",
        "desc": "As the Gunner, both of your bullets hit a wolf, serial killer, or cultist",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Streetwise",
        "desc": "Find a different wolf, serial killer, or cultist 4 nights in a row as the detective",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Speed Dating",
        "desc": "Have the bot select you as a lover (cupid failed to choose)",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Even a Stopped Clock is Right Twice a Day",
        "desc": "As the Fool, have at least two of your visions be correct by the end of the game",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "So Close!",
        "desc": "As the Tanner, be tied for the most lynch votes",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Cultist Convention",
        "desc": "Be one of 10 or more cultists alive at the end of a game",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Self Loving",
        "desc": "As cupid, pick yourself as one of the lovers",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Should've Said Something",
        "desc": "As a wolf, your pack eats your lover (first night does not count)",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Tanner Overkill",
        "desc": "As the Tanner, have everyone (but yourself) vote to lynch you",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Serial Samaritan",
        "desc": "As the Serial Killer, kill at least 3 wolves in single game",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Cultist Fodder",
        "desc": "Be the cultist that is sent to attempt to convert the Cult Hunter",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Lone Wolf",
        "desc": "In a chaos game of 10 or more people, be the only wolf - and win",
        "type": "game-end",
        "notes": "",
    },
    {"name": "Pack Hunter", "desc": "Be one of 7 living wolves at one time", "type": "instantaneous", "notes": ""},
    {
        "name": "Saved by the Bull(et)",
        "desc": "As a villager, the wolves match the number of villagers, but the game does not end because the gunner has a bullet",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "In for the Long Haul",
        "desc": "Survive for at least an hour in a single game",
        "type": "instantaneous",
        "notes": "",
    },
    {"name": "OH SHI-", "desc": "Kill your lover on the first night", "type": "instantaneous", "notes": ""},
    {"name": "Veteran", "desc": "Play 500 games.  You can now join @werewolfvets", "type": "game-end", "notes": ""},
    {"name": "No Sorcery!", "desc": "As a wolf, kill your sorcerer", "type": "instantaneous", "notes": ""},
    {
        "name": "Cultist Tracker",
        "desc": "As the cultist hunter, kill at least 3 cultists in one game",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "I'M NOT DRUN-- *BURPPP*",
        "desc": "As the clumsy guy, have at least 3 correct lynches by the end of the game",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Wuffie-Cult",
        "desc": "As the alpha wolf, successfully convert at least 3 victims into wolves",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Did you guard yourself?",
        "desc": "As the guardian angel, survive after 3 tries guarding an unattacked wolf",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Spoiled Rich Brat",
        "desc": "As the prince, still gets lynched even after revealing your identity",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Three Little Wolves and a Big Bad Pig",
        "desc": "As the sorcerer, survive a game with three or more alive wolves",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "President",
        "desc": "As the mayor, successfully cast 3 lynch votes after revealing",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "I Helped!",
        "desc": "As a wolf cub, the alive pack has 2 successful eat attempts after you die",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "It Was a Busy Night!",
        "desc": "During the same night, got visited by 3 or more different visiting roles",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Strongest Alpha",
        "desc": "As the alpha wolf, successfully infect the serial killer!",
        "type": "game-end",
        "notes": "",
    },
    {"name": "Am I Your Seer?", "desc": "As the fool, correctly spot the beholder", "type": "game-end", "notes": ""},
    {
        "name": "Demoted by the Death",
        "desc": "As the hunter, shoot the wise elder with your final shot and die as lowly villager",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Wasted Silver",
        "desc": "As the blacksmith, spread your silver dust the same day that the sandman sings",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Trustworthy!",
        "desc": "As the wolf man, survive and win the game after being checked by seer",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Deep Love",
        "desc": "As the doppelgänger, choose your lover as role model. What a deep love &lt;3",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Time to retire...",
        "desc": "As the sorcerer, be the last person alive in the village and lose the game",
        "type": "game-end",
        "notes": "",
    },
    {"name": "Seeing between Teams", "desc": "Be in a seer/sorcerer couple", "type": "instantaneous", "notes": ""},
    {
        "name": "Just a Beardy Guy..?",
        "desc": "As the wolf man, be infected by the alpha wolf and become a real werewolf. AWOOOOOOO!",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "That Came Unexpected!",
        "desc": "As tanner, be lynched and win the game when there are only 3 persons left",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Now I'm Blind",
        "desc": "As the oracle, fail to get a vision because everyone else has the same role.",
        "type": "instantaneous",
        "notes": "Can be completed with 3 players one of which is a killer. Oracle checks the killer while the killer kills the non-oracle player.",
    },
    {
        "name": "Every Man for Himself!",
        "desc": "As the pacifist, save yourself from being lynched (at least 50% of votes have been cast for you already)",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "My Sweetie so Strong!",
        "desc": "Be in love with the pacifist, and get saved from being lynched by them (at least 50% of votes have been cast for you already)",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Cult Leader",
        "desc": "Be a cultist from the beginning of the game, survive and win.",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Thanks, Junior!",
        "desc": "After the wolf pack ate the Drunk, you turn into a wolf and can try to eat someone while the rest of the wolf pack is drunk!",
        "type": "instantaneous",
        "notes": "",
    },
    {"name": "Death Village", "desc": "Participate in a game that has no winner.", "type": "game-end", "notes": ""},
    {
        "name": "I Lost my Wisdom",
        "desc": "As the wise elder, change your role! Suddenly you're not that wise anymore...",
        "type": "instantaneous",
        "notes": "",
    },
    {"name": "Affectionate", "desc": "As the harlot, visit your lover!", "type": "instantaneous", "notes": ""},
    {
        "name": "Lucky Day",
        "desc": "As the Alpha Wolf, infect the drunk and stay sober! Phew...",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Condition Red!",
        "desc": "As the last wolf alive, eat the traitor. Oh no!",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Indestructible",
        "desc": "Become Doppelgänger or Wild Child with your role model being yourself!",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Psychopath Killer",
        "desc": "As the serial killer, win a game with 35 players!",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Today's Special!",
        "desc": "Be the role only available on special events!",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Romeo and Juliet",
        "desc": "Be in love with the tanner, and win by lynching your lover!",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Really bad luck",
        "desc": "As a serial killer, stumble in a grave, then kill someone randomly and get fought off by the guardian angel.",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Domino",
        "desc": "As a hunter, shoot another hunter causing them to shoot as well.",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Double Shot",
        "desc": "As the hunter or the gunner, shoot a bad role who is in love with another bad role!",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Playing with the Fire",
        "desc": "As the arsonist, burn 5 or more houses in one night.",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Firework",
        "desc": "As the arsonist, burn 10 or more houses in one night! What a nice firework :)",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Cold as Ice",
        "desc": "As the Snow Wolf, freeze the harlot. Their love is cold as ice.",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Good Choice... For You",
        "desc": "As the chemist, visit a player and survive 3 times in a single game.",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Increase the Pack!",
        "desc": "After the wolf cub died, infect 2 players as the alpha wolf!",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Firefighter",
        "desc": "As the guardian angel, clean three houses of kerosene.",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Helpful Paranoia",
        "desc": "As the hunter, shoot two attackers!",
        "type": "instantaneous",
        "notes": "Easiest done with cults failing conversion twice and getting shot but can also be completed with wolves. Important that its a lone wolf so the hunter survives the first attack because its gauranteed kill on hunter with a pack.",
    },
    {
        "name": "S-Tier Hunter",
        "desc": "As the hunter, take down a wolf and a cultist in the same night!",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Triple Kill",
        "desc": "As a serial killer or wolf, have at least three people die by your hand in the same night!",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Resist the Beast",
        "desc": "As a trio of wild child, traitor, and cursed, all remain human and win the game with the village.",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "At least you tried...",
        "desc": "As the guardian angel, save someone at night only to watch them die to the chemist's poison.",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Lucky Night",
        "desc": "Survive the chemist's visit and enjoy the harlot's visit in the same night!",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "In the Middle of the Trouble",
        "desc": "As the guardian angel, save a werewolf from an attack and survive!",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Am I hallucinating?!",
        "desc": "As the fool, see a role which the seer can never see",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Going Down with my Beer",
        "desc": "As a villager, die by visiting the bar the night it is set on fire.",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Alcoholics Anonymous",
        "desc": "Be one of 3 or more drunks at the end of the game.",
        "type": "game-end",
        "notes": "",
    },
    {
        "name": "Liquid Business",
        "desc": "As the barkeep, have your bar visited by 3 or more villagers in one night.",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Traffic Control",
        "desc": "As the chef, find out that a person was visited by 3 people in one night!",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Definitely Dead",
        "desc": "As the chef, track a person who is murdered that night.",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Going Out Of Business",
        "desc": "As the barkeep in a game of 10 players or more, have no visitors in your bar for 3 nights in a row!",
        "type": "instantaneous",
        "notes": "",
    },
    {
        "name": "Food Waste",
        "desc": "As the chef, track 3 or more different people who did not leave their house and did not have visitors.",
        "type": "instantaneous",
        "notes": "",
    },
]
